// <auto-generated />
using System;
using FoodLog.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FoodLog.Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200714121413_NewFood")]
    partial class NewFood
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FoodLog.Domain.Entity.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryType")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Grams")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryType = 7,
                            Date = new DateTime(2020, 7, 14, 12, 14, 12, 845, DateTimeKind.Utc).AddTicks(3849),
                            Grams = 350,
                            Name = "Tuna"
                        },
                        new
                        {
                            Id = 2,
                            CategoryType = 0,
                            Date = new DateTime(2020, 7, 14, 12, 14, 12, 845, DateTimeKind.Utc).AddTicks(4984),
                            Grams = 300,
                            Name = "Potato"
                        },
                        new
                        {
                            Id = 3,
                            CategoryType = 8,
                            Date = new DateTime(2020, 7, 14, 12, 14, 12, 845, DateTimeKind.Utc).AddTicks(4987),
                            Grams = 100,
                            Name = "Mozzarella"
                        });
                });

            modelBuilder.Entity("FoodLog.Domain.Entity.Nutrient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Grams")
                        .HasColumnType("float");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("NutrientType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Nutrients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Grams = 1.3,
                            ItemId = 1,
                            NutrientType = 0
                        },
                        new
                        {
                            Id = 2,
                            Grams = 0.0,
                            ItemId = 1,
                            NutrientType = 1
                        },
                        new
                        {
                            Id = 3,
                            Grams = 28.0,
                            ItemId = 1,
                            NutrientType = 2
                        },
                        new
                        {
                            Id = 4,
                            Grams = 0.089999999999999997,
                            ItemId = 2,
                            NutrientType = 0
                        },
                        new
                        {
                            Id = 5,
                            Grams = 17.0,
                            ItemId = 2,
                            NutrientType = 1
                        },
                        new
                        {
                            Id = 6,
                            Grams = 2.0,
                            ItemId = 2,
                            NutrientType = 2
                        },
                        new
                        {
                            Id = 7,
                            Grams = 17.0,
                            ItemId = 3,
                            NutrientType = 0
                        },
                        new
                        {
                            Id = 8,
                            Grams = 3.1000000000000001,
                            ItemId = 3,
                            NutrientType = 1
                        },
                        new
                        {
                            Id = 9,
                            Grams = 28.0,
                            ItemId = 3,
                            NutrientType = 2
                        });
                });

            modelBuilder.Entity("FoodLog.Domain.Entity.Nutrient", b =>
                {
                    b.HasOne("FoodLog.Domain.Entity.Item", null)
                        .WithMany("Nutrients")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
